plugins:
  geoblocking_enabled: true
  geoblocking_blocked_redirect: ""
  geoblocking_blocked_countries:
    type: list
    default: "EU|AD|AL|AT|BA|BE|BG|BY|CH|CS|CZ|DE|DK|EE|ES|FI|FO|FR|FX|GB|GI|GR|HR|HU|IE|IS|IT|LI|LT|LU|LV|MC|MD|MK|MT|NL|NO|PL|PT|RO|SE|SI|SJ|SK|SM|UA|VA"
    list_type: named
    choices: "DiscourseGeoblocking::COUNTRY_CODES"
  geoblocking_allowed_countries:
    type: list
    default: ""
    list_type: named
    choices: "DiscourseGeoblocking::COUNTRY_CODES"
