plugins:
  geoblocking_enabled: false
  geoblocking_blocked_redirect: ""
  geoblocking_blocked_countries:
    type: list
    default: ""
    list_type: named
    choices: "DiscourseGeoblocking::COUNTRY_CODES"
  geoblocking_allowed_countries:
    type: list
    default: ""
    list_type: named
    choices: "DiscourseGeoblocking::COUNTRY_CODES"
  geoblocking_blocked_geoname_ids:
    type: list
    default: ""
    list_type: compact
  geoblocking_allowed_geoname_ids:
    type: list
    default: ""
    list_type: compact
